force-app/async/main/default/objects/AsyncTask__c/AsyncTask__c.object-meta.xml
<CustomObject>
    <description>Represents a task that will be run asynchronously by the system.</description>
    <label>Async Task</label>
    <nameField>
        <label>Async Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Async Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/async/main/default/objects/AsyncTask__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the task</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/async/main/default/objects/AsyncTask__c/fields/ExecutionCount__c.field-meta.xml
<CustomField>
    <fullName>ExecutionCount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Execution Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/async/main/default/objects/AsyncTask__c/fields/HandlerClassName__c.field-meta.xml
<CustomField>
    <fullName>HandlerClassName__c</fullName>
    <description>Name of the handler class for this task</description>
    <label>Handler Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/async/main/default/objects/AsyncTask__c/fields/OnHold__c.field-meta.xml
<CustomField>
    <fullName>OnHold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, this task execution will be skipped</description>
    <label>On hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/async/main/default/classes/AsyncTaskInfoTest.cls
@IsTest(isParallel=true)
private class AsyncTaskInfoTest {
    @IsTest
    private static void testConstructor() {
        AsyncTask__c task = new AsyncTask__c();
        task.Description__c = 'desc';
        task.ExecutionCount__c = 4;
        task.HandlerclassName__c = 'DummyClass';
        task.OnHold__c = true;
        insert task;

        AsyncTaskInfo info = new AsyncTaskInfo(task);
        System.assertEquals('desc', info.getDescription(), 'incorrect getDescription() value');
        System.assertEquals(task.CreatedDate, info.getCreatedDate(), 'incorrect getCreatedDate() value');
        System.assertEquals(4, info.getExecutionCount(), 'incorrect getExecutionCount() value');
        System.assertNotEquals(null, info.getTaskId(), 'taskId is null');
    }

    @IsTest
    private static void testOnHold() {
        AsyncTask__c task = new AsyncTask__c();
        AsyncTaskInfo info = new AsyncTaskInfo(task);
        System.assertEquals(false, info.isOnHold(), 'incorrect isOnHold() value');
        info.setOnHold(true);
        System.assert(info.isOnHold(), 'incorrect isOnHold() value');
    }

    @IsTest
    private static void testSkipUntil() {
        AsyncTask__c task = new AsyncTask__c();
        AsyncTaskInfo info = new AsyncTaskInfo(task);
        System.assertEquals(null, info.getSkipUntil(), 'incorrect skipUntil() value');
        DateTime now = DateTime.now();
        info.setSkipUntil(now);
        System.assertEquals(now, info.getSkipUntil(), 'incorrect skipUntil() value');
    }

    @IsTest
    private static void testPriority() {
        AsyncTask__c task = new AsyncTask__c();
        AsyncTaskInfo info = new AsyncTaskInfo(task);
        System.assertEquals(0, info.getPriority(), 'incorrect getPriority() value');
        info.setPriority(100);
        System.assertEquals(100, info.getPriority(), 'incorrect getPriority() value');
    }
}