force-app/async/main/default/objects/AsyncTask__c/AsyncTask__c.object-meta.xml
<CustomObject>
    <description>Represents a task that will be run asynchronously by the system.</description>
    <label>Async Task</label>
    <nameField>
        <label>Async Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Async Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/async/main/default/objects/AsyncTask__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the task</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/async/main/default/objects/AsyncTask__c/fields/ExecutionCount__c.field-meta.xml
<CustomField>
    <fullName>ExecutionCount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Execution Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/async/main/default/objects/AsyncTask__c/fields/HandlerClassName__c.field-meta.xml
<CustomField>
    <fullName>HandlerClassName__c</fullName>
    <description>Name of the handler class for this task</description>
    <label>Handler Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/async/main/default/objects/AsyncTask__c/fields/OnHold__c.field-meta.xml
<CustomField>
    <fullName>OnHold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, this task execution will be skipped</description>
    <label>On hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/async/main/default/objects/AsyncTask__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Priority</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <inlineHelpText>Higher value -> higher priority</inlineHelpText>
</CustomField>

force-app/async/main/default/objects/AsyncTask__c/fields/SkipUntil__c.field-meta.xml
<CustomField>
    <fullName>SkipUntil__c</fullName>
    <description>The execution of this task will be skipped until this moment</description>
    <label>Skip Until</label>
    <type>DateTime</type>
</CustomField>

force-app/async/main/default/classes/AsyncTask.cls
/**
 * @description AsyncTask represents an asynchronous task
 * in the system.
 */
@SuppressWarnings('PMD.ApexCRUDViolation')
public without sharing class AsyncTask {
    /**
     * @description newTask() creates an async task in the database.
     *
     * @param config the task configuration
     * @return the task ID
     */
    public static Id newTask(AsyncTask.Configuration config) {
        AsyncTask__c task = AsyncTask.build(config);
        insert task;
        if (config.payload != null) {
            Attachment payload = AsyncTask.buildPayload(task, config.payload);
            insert payload;
        }
        return task.Id;
    }

    /**
     * @description newTasks() bulk creates new async tasks
     *
     * @param configs a collection of task configurations
     */
    public static void newTasks(List<AsyncTask.Configuration> configs) {
        if (configs == null || configs.isEmpty()) {
            return;
        }

        List<AsyncTask__c> tasks = new List<AsyncTask__c>();
        for (AsyncTask.Configuration config : configs) {
            tasks.add(AsyncTask.build(config));
        }
        insert tasks;

        List<Attachment> attachments = new List<Attachment>();
        Integer index = 0;
        for (AsyncTask__c task : tasks) {
            AsyncTask.Configuration config = configs.get(index);
            if (config.payload != null) {
                attachments.add(AsyncTask.buildPayload(task, config.payload));
            }
            index++;
        }
        insert attachments;
    }

    /**
     * @description builds the attachement payload for the task
     * The attachement is not saved in the db at this stage.
     *
     * @param task the task to link the attachment to
     * @param content the JSON serialized payload
     * @return the attachment object.
     */
    private static Attachment buildPayload(AsyncTask__c task, String content) {
        Attachment payload = new Attachment();
        payload.ContentType = 'application/json';
        payload.Body = Blob.valueOf(content);
        payload.Description = 'Async task payload';
        payload.IsPrivate = true;
        payload.Name = 'async_task_payload';
        payload.ParentId = task.Id;
        return payload;
    }

    /**
     * @description builds an async task from the given configuration.
     * The task is not saved in the db at this stage.
     *
     * @param config the async task configuration
     * @return the newly built async task.
     */
    private static AsyncTask__c build(AsyncTask.Configuration config) {
        AsyncTask__c task = new AsyncTask__c();
        task.Description__c = config.description;
        task.HandlerClassName__c = config.handlerClass.getName();
        task.ExecutionCount__c = 0;
        task.Priority__c = config.priority;
        task.OnHold__c = config.onHold;
        task.SkipUntil__c = config.skipUntil;
        return task;
    }

    /**
     * @description an Async task configuration
     */
    public class Configuration {
        /** @description description of the task */
        public String description { get; private set; }
        /** @description System.Type of the task handler */
        public System.Type handlerClass { get; private set; }
        /** @description serialized paylod of the task */
        public String payload { get; private set; }
        /** @description priority */
        public Integer priority {
            get {
                if (this.priority == null) {
                    return 0;
                }
                return this.priority;
            }
            set;
        }
        /** @description sets the task on hold */
        public Boolean onHold {
            get {
                if (this.onHold == null) {
                    this.onHold = false;
                }
                return this.onHold;
            }
            set;
        }
        /** @description skip the task execution until this moment */
        public DateTime skipUntil { get; set; }

        /**
         * @description contructor.
         *
         * @param description the task description (mandatory)
         * @param handlerClass the class which will handle this task execution
         */
        public Configuration(String description, Type handlerClass) {
            this.description = description;
            this.handlerClass = handlerClass;
        }

        /**
         * @description contructor.
         *
         * @param description the task description (mandatory)
         * @param handlerClass the class which will handle this task execution
         * @param payload the payload to link to this task. Note that the payload will be serialized
         *     to JSON at this stage so it is safe to modify after the creation of the configuration
         */
        public Configuration(String description, Type handlerClass, Object payload) {
            System.assert(description != null, 'description is required');
            System.assert(handlerClass != null, 'handlerClass is required');
            if (payload != null) {
                this.payload = JSON.serializePretty(payload);
            }

            this.description = description;
            this.handlerClass = handlerClass;
        }
    }
}